# Generated by Django 3.1.7 on 2021-04-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('nodes_used', models.IntegerField(null=True)),
            ],
        ),
    ]
